---
author: "Trist'n Joseph (trisxcjoseph@gmail.com)"
---

#Set up
```{r}
library(readr)
library(tidyverse)
library(ggthemes) # contains the theme that I will be using for the graphs

```

Data retrieved from a publicly available data repository (https://github.com/RamiKrispin/coronavirus). 

#Overall cases
```{r}

covid_df <- read_csv("E:/Projects/Covid19/covid19_autoupdate.csv")
glimpse(covid_df)
covid_df$date <- parse_date(covid_df$date, format="%m/%d/%Y")
covid_df$type <- parse_factor(covid_df$type)
anyNA(covid_df)

confirmed_cases <- covid_df%>%
  filter(type=="confirmed")%>%
  select(c("date", "country", "cases"))

confirmed_cases_total <- confirmed_cases%>%
  group_by(date)%>%
  summarise(Total_cases= sum(cases))%>% 
  # aggregate cases by day
  mutate(Cumulative_cases = cumsum(Total_cases)) 
  # calculate the cumulative number of cases
 
ggplot(confirmed_cases_total, aes(x=date, y=Cumulative_cases))+
  geom_line()+
  scale_y_log10()+
  scale_x_date(date_breaks = "months", date_labels = "%b-%Y")+ 
  # shows the month and year as x-axis tick markers
  ylab("Cumulative Cases")+
  xlab("Date")+
  ggtitle("Cumulative World Covid-19 Cases per day")+
  theme_tufte()

```

#USA vs World
```{r}

usa_vs_world_us <- confirmed_cases%>%
  filter(country == "US")%>%
  group_by(date)%>%
  summarise(Total_cases= sum(cases))%>%
  mutate(Cumulative_cases = cumsum(Total_cases))
usa_vs_world_us$Location <- as.factor(rep("USA", nrow(usa_vs_world_us))) # creates a membership variable

usa_vs_world_notus <- confirmed_cases%>%
  filter(country != "US")%>%
  group_by(date)%>%
  summarise(Total_cases= sum(cases))%>%
  mutate(Cumulative_cases = cumsum(Total_cases))
usa_vs_world_notus$Location <- as.factor(rep("Not USA", nrow(usa_vs_world_notus))) # creates a membership variable

usa_vs_world <- rbind(usa_vs_world_us, usa_vs_world_notus)

ggplot(usa_vs_world, aes(x=date, y=Cumulative_cases, color=Location))+ 
  # 'color' colours individual lines on the plot by the memebership variable
  geom_line()+
  scale_y_log10()+
  scale_x_date(date_breaks = "months", date_labels = "%b-%Y")+
  xlab("Date")+ 
  ylab("Cumulative Cases")+ 
  ggtitle("Cumulative Covid-19 Cases per day, USA vs The World")+
  theme_tufte()

```

#China vs USA
```{r}

confirmed_cases_USA <- usa_vs_world_us
confirmed_cases_USA <- rename(confirmed_cases_USA,"Country"="Location")

confirmed_cases_China <- confirmed_cases%>%
  filter(country == "China")%>%
  group_by(date)%>%
  summarise(Total_cases= sum(cases))%>%
  mutate(Cumulative_cases = cumsum(Total_cases))
confirmed_cases_China$Country <- as.factor(rep("China", nrow(confirmed_cases_China)))

confirmed_cases_China <- rbind(confirmed_cases_China, confirmed_cases_USA)

ggplot(confirmed_cases_China, aes(x=date, y=Cumulative_cases, color=Country))+
  geom_line()+
  scale_y_log10()+
  scale_x_date(date_breaks = "months", date_labels = "%b-%Y")+
  xlab("Date")+ 
  ylab("Cumulative Cases")+
  ggtitle("Cumulative Covid-19 Cases per day, USA vs China")+
  theme_tufte()

```

#Which countries were hit the hardest ?
```{r}

Hardest_hit_Countries <- confirmed_cases%>%
  group_by(country)%>%
  summarise(Total_cases = sum(cases))%>%
  arrange(desc(Total_cases))%>%
  top_n(5) # selects the top 5 countries 

Hardest_hit_Countries<-rename(Hardest_hit_Countries,"Country"="country")
Hardest_hit_Countries

confirmed_cases_Brazil <- confirmed_cases%>%
  filter(country == "Brazil")%>%
  group_by(date)%>%
  summarise(Total_cases= sum(cases))%>%
  mutate(Cumulative_cases = cumsum(Total_cases))
confirmed_cases_Brazil$Country <- as.factor(rep("Brazil", nrow(confirmed_cases_Brazil)))

# loop through the hardest hit countries and create a df for reach 
# at the time of creating this, the top 5 countries are: USA, Brazil, Russia, India & South Africa

confirmed_cases_Hardest_hit_countries <- rbind(confirmed_cases_USA, confirmed_cases_Brazil, confirmed_cases_Russia, confirmed_cases_India, confirmed_cases_SouthAfrica)

confirmed_cases_Hardest_hit_countries <- confirmed_cases_Hardest_hit_countries%>%
  filter(date >= "2020-03-15") # filtered the date to make the plot easier to read

hardest_hit_graph <- ggplot(confirmed_cases_Hardest_hit_countries)+
  geom_line(mapping=aes(x=date, y=Cumulative_cases, color=Country))+
  scale_x_date(date_breaks = "months", date_labels = "%b-%Y")+
  xlab("Date")+
  ylab("Cumulative Cases") + 
  ggtitle("Cumulative Covid-19 Cases by Hardest Hit Countries")+
  theme_tufte()

lockdown_countries <- tribble(
  ~date, ~event, 
  "2020-05-05", "Brazil",
 # "2020-03-23", "South Africa",
  "2020-03-19", "USA\nLockdown",
  "2020-03-30", "Russia",
  "2020-03-24", "India &\nSouth Africa"
)%>%
  mutate(date = as.Date(date))

# this plot contains dashed markers to show when each country went into lockdown 
hardest_hit_graph + 
  geom_vline(aes(xintercept = date), data = lockdown_countries, linetype = "dashed")+
  geom_text(aes(x=date, label = event), data = lockdown_countries, y=c(6000000, 1000000, 5000000, 3000000)) 
  
```

#Hardest his versus the world
```{r}

rest_of_world <- confirmed_cases%>%
  filter(country !="US" | country !="Brazil" |country !="Russia"|country !="India"|country !="South Africa"| country !="China")%>%
  group_by(date)%>%
  summarise(Total_cases= sum(cases))%>%
  mutate(Cumulative_cases = cumsum(Total_cases))
rest_of_world$Country <- as.factor(rep("Rest of world", nrow(rest_of_world)))

Hardest_hit_vs_world <- rbind(confirmed_cases_Hardest_hit_countries, rest_of_world)
Hardest_hit_vs_world <- Hardest_hit_vs_world%>%
  filter(date >= "2020-03-15") # filtered the date to make the plot easier to read

ggplot(Hardest_hit_vs_world)+
  geom_line(mapping=aes(x=date, y=Cumulative_cases, color=Country))+
  scale_y_log10()+
  scale_x_date(date_breaks = "months", date_labels = "%b-%Y")+
  xlab("Date")+
  ylab("Cumulative Cases") + 
  ggtitle("Cumulative Covid-19 Cases,\nHardest Hit Countries vs The World")+
  theme_tufte()

```

#Hardest hit up until April
```{r}

Hardest_hit_Countries_before_april <- confirmed_cases%>%
  filter(date <= "2020-04-01")%>%
  group_by(country)%>%
  summarise(Total_cases = sum(cases))%>%
  arrange(desc(Total_cases))%>%
  top_n(5)

```


#Majority of worldwide cases
```{r}

share_of_cases <- confirmed_cases%>%
  group_by(country)%>%
  summarise(Total_cases = sum(cases))%>%
  mutate(p_of_total_cases = (Total_cases/sum(Total_cases))*100)%>%
  arrange(desc(p_of_total_cases))%>%
  mutate(cumulative_p_of_total_cases = cumsum(p_of_total_cases))


```

#US Progression 
```{r}

usa_events <- tribble(
  ~date, ~event, 
  "2020-01-30", "Global Health\nEmergency", 
  "2020-03-11", "Pandemic\nDeclared",
)%>%
  mutate(date = as.Date(date))

ggplot(confirmed_cases_USA) +
  geom_line(mapping = aes(x=date, y = Cumulative_cases)) +
  geom_smooth(mapping = aes(x=date, y = Cumulative_cases), method = "loess")+
  geom_vline(aes(xintercept = date), data = usa_events, linetype = "dashed")+
  geom_text(aes(x=date, label = event), data = usa_events, y=3000000)+
  annotate("rect", xmin =as.Date("2020-03-19", "%Y-%m-%d"), xmax = as.Date("2020-04-24", "%Y-%m-%d"), ymin = 0, ymax=6000000, alpha = 0.25)+
  annotate("text", x = as.Date("2020-04-06", "%Y-%m-%d"), y= 4000000, label = "All States Lockdown")+
  theme_tufte()+
  scale_x_date(date_breaks = "months", date_labels = "%b-%Y")+
  xlab("Date")+
  ylab("Cumulative Cases")+
  ggtitle("United States Cumulative COVID-19 Cases")

ggplot(usa_vs_world_notus, mapping = aes(x=date, y=Cumulative_cases))+
  geom_line()+
  geom_smooth(method = "loess")+
  scale_y_log10()+
  scale_x_date(date_breaks = "months", date_labels = "%b-%Y")+
  xlab("Date")+
  ylab("Cumulative Cases")+
  ggtitle("Rest of World Cumulative COVID-19 Cases")+
  theme(panel.background = element_rect(fill = "white", colour = "black"))+
  geom_vline(aes(xintercept = date), data = usa_events, linetype = "dashed")+
  geom_text(aes(x=date, label = event), data = usa_events, y=1500000)

```
